version: "3"
services:
  db:
    image: postgres:11.2-alpine
    env_file:
      - development.env
    ports:
      - "5432:5432"
    volumes:
      - "/var/lib/postgresql/data"
  server:
    depends_on:
      - db
    ports:
      - "3001:3001"
    build: .
