version: "3"
services:
  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: ""
      POSTGRES_DB: ""
    volumes:
      - .pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    # image: name goes here
    depends_on:
      - db
    ports:
      - "3000:3000"
    build: .
