version: "3"
services:
  db:
    image: postgres:11.2-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    restart: on-failure
  server:
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3001:3001"
    build: .
volumes:
  dbdata:
