version: "3"
services:
  db:
    image: postgres:11.2-alpine
    env_file: development.postgres.env
    ports:
      - "5432:5432"
    volumes:
      - "psqldb:/var/lib/postgresql/data"
    restart: on-failure
  server:
    depends_on:
      - db
    env_file:
      - development.server.env
    ports:
      - "3000:3000"
    build: .
volumes:
  psqldb:
